version: '3.8'

volumes:
  prometheus-data: {}
  grafana-data: {}
  redis-data: {}
  mqtt-data: {} 

services:
  distributor:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: distributor.py
    environment:
      PORT: 80
    ports:
      - 5000:80
    depends_on:
      - redis
      - mosquitto 

  factory_line1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: factory_line1.py
    depends_on:
      - mosquitto  

  factory_line2:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: factory_line2.py
    depends_on:
      - mosquitto  

  supplier:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: supplier.py
    depends_on:
      - mosquitto 

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - mqtt-data:/mosquitto/data
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"  

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data

