{
 "title": "Products",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total orders",
   "type": "stat",
   "description": "Total number of product orders in period.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(distributor_product_request_duration_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average order response time",
   "type": "stat",
   "description": "Average response time to fulfill orders",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(distributor_product_request_duration_sum[$__range]) / rate(distributor_product_request_duration_count[$__range])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stock level",
   "type": "bargauge",
   "description": "Stock levels for all products.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "distributor_product_count", "legendFormat": "{{product}}" }
   ]
  },
  {
   "title": "Stock over time",
   "type": "timeseries",
   "description": "Stock level over time for all products.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "distributor_product_count", "legendFormat": "{{product}}" }
   ]
  }
 ]
}